joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

head_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - head_j0
      - head_j1

zlift_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - zlift_j0

body_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - torso_j0
      - torso_j1
      - torso_j2

arm_r_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - right_arm_j0
      - right_arm_j1
      - right_arm_j2
      - right_arm_j3
      - right_arm_j4
      - right_arm_j5
      - right_arm_j6

    

