head:
  right_arm_look_at:
    header:
      frame_id: ''
      seq: 0
      stamp:
        nsecs: 0
        secs: 0
    joint_names:
    - head_j0
    - head_j1
    points:
    - accelerations: []
      effort: []
      positions:
      - -0.5
      - -0.0
      time_from_start:
        nsecs: 0
        secs: 3
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - -0.5
      - -0.0
      time_from_start:
        nsecs: 0
        secs: 6
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - -0.7
      - -0.0
      time_from_start:
        nsecs: 500000000
        secs: 6
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - -0.4
      - -0.0
      time_from_start:
        nsecs: 0
        secs: 7
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - -0.4
      - -0.0
      time_from_start:
        nsecs: 0
        secs: 9
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - -0.65
      - -0.4
      time_from_start:
        nsecs: 0
        secs: 11
      velocities: []
  right_arm_hand_over_retreat:
    header:
      frame_id: ''
      seq: 0
      stamp:
        nsecs: 0
        secs: 0
    joint_names:
    - head_j0
    - head_j1
    points:
    - accelerations: []
      effort: []
      positions:
      - 0.06810788168569369
      - 0.024211821880725938
      time_from_start:
        nsecs: 500000000
        secs: 2
      velocities: []
  right_arm_hand_over_approach_low:
    header:
      frame_id: ''
      seq: 0
      stamp:
        nsecs: 0
        secs: 0
    joint_names:
    - head_j0
    - head_j1
    points:
    - accelerations: []
      effort: []
      positions:
      - 0.06810788168569369
      - 0.024211821880725938
      time_from_start:
        nsecs: 500000000
        secs: 0
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - -0.6190050926174717
      - -0.340251839606687
      time_from_start:
        nsecs: 0
        secs: 2
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - -0.6190050926174717
      - -0.340251839606687
      time_from_start:
        nsecs: 500000000
        secs: 3
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - 0.07012835126995719
      - 0.013848243195630968
      time_from_start:
        nsecs: 0
        secs: 5
      velocities: []
  right_arm_hand_over_approach_high:
    header:
      frame_id: ''
      seq: 0
      stamp:
        nsecs: 0
        secs: 0
    joint_names:
    - head_j0
    - head_j1
    points:
    - accelerations: []
      effort: []
      positions:
      - 0.06810788168569369
      - 0.024211821880725938
      time_from_start:
        nsecs: 500000000
        secs: 0
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - -0.6190050926174717
      - -0.340251839606687
      time_from_start:
        nsecs: 0
        secs: 2
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - -0.6190050926174717
      - -0.340251839606687
      time_from_start:
        nsecs: 500000000
        secs: 3
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - 0.07012835126995719
      - 0.013848243195630968
      time_from_start:
        nsecs: 0
        secs: 5
      velocities: []
left_arm:
  right_arm_hand_over_retreat:
    header:
      frame_id: ''
      seq: 0
      stamp:
        nsecs: 0
        secs: 0
    joint_names:
    - left_arm_j0
    - left_arm_j1
    - left_arm_j2
    - left_arm_j3
    - left_arm_j4
    - left_arm_j5
    - left_arm_j6
    points:
    - accelerations: []
      effort: []
      positions:
      - -0.12700188970630603
      - -0.1022199138850624
      - 0.4873116351145129
      - 0.3798519229531993
      - -1.6
      - -0.018112950389108578
      - -0.07296702755165403
      time_from_start:
        nsecs: 500000000
        secs: 2
      velocities: []
  right_arm_hand_over_approach_low:
    header:
      frame_id: ''
      seq: 0
      stamp:
        nsecs: 0
        secs: 0
    joint_names:
    - left_arm_j0
    - left_arm_j1
    - left_arm_j2
    - left_arm_j3
    - left_arm_j4
    - left_arm_j5
    - left_arm_j6
    points:
    - accelerations: []
      effort: []
      positions:
      - -0.12700188970630603
      - -0.1022199138850624
      - 0.4873116351145129
      - 0.3798519229531993
      - -1.1003225948366255
      - -0.018112950389108578
      - -0.07296702755165403
      time_from_start:
        nsecs: 500000000
        secs: 1
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - -0.12754880373957856
      - -0.09212251631245748
      - 0.4874654746630377
      - 0.38011293411678004
      - -1.1002320090911322
      - -0.017911202154254707
      - -0.07306856004438961
      time_from_start:
        nsecs: 0
        secs: 2
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - -0.2553008593153001
      - -0.30152614464139077
      - 0.3716320829364964
      - 0.8
      - -0.7970009176213039
      - -0.48510780750821914
      - 0.08317488674549287
      time_from_start:
        nsecs: 500000000
        secs: 3
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - -0.2255884174137096
      - -0.24897860643444644
      - 0.47509286644205164
      - 0.9
      - -3.0565501344194943
      - -0.4255697748080526
      - -0.1962893405389572
      time_from_start:
        nsecs: 0
        secs: 5
      velocities: []
  right_arm_hand_over_approach_high:
    header:
      frame_id: ''
      seq: 0
      stamp:
        nsecs: 0
        secs: 0
    joint_names:
    - left_arm_j0
    - left_arm_j1
    - left_arm_j2
    - left_arm_j3
    - left_arm_j4
    - left_arm_j5
    - left_arm_j6
    points:
    - accelerations: []
      effort: []
      positions:
      - 0.02754880373957856
      - -0.09212251631245748
      - 0.4874654746630377
      - 0.68011293411678004
      - -1.1002320090911322
      - -0.017911202154254707
      - -0.07306856004438961
      time_from_start:
        nsecs: 900000000
        secs: 0
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - 0.0553008593153001
      - -0.30152614464139077
      - 0.3716320829364964
      - 1.5015470654539979
      - -0.7970009176213039
      - -0.48510780750821914
      - 0.08317488674549287
      time_from_start:
        nsecs: 000000000
        secs: 3
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - -0.3
      - -0.24897860643444644
      - 0.47509286644205164
      - 1.2
      - -3.0565501344194943
      - -0.4255697748080526
      - -0.1962893405389572
      time_from_start:
        nsecs: 0
        secs: 5
      velocities: []
left_hand:
  right_arm_hand_over_retreat:
    header:
      frame_id: ''
      seq: 0
      stamp:
        nsecs: 0
        secs: 0
    joint_names:
    - left_hand_j0
    - left_hand_j1
    - left_hand_j2
    - left_hand_j3
    - left_hand_j4
    points:
    - accelerations: []
      effort: []
      positions:
      - 1.5947399982060031
      - 0.16161399972572643
      - 0.0254732997155211
      - 0.04041141662683649
      - 0.10731468046050929
      time_from_start:
        nsecs: 500000000
        secs: 3
      velocities: []
  right_arm_hand_over_approach_low:
    header:
      frame_id: ''
      seq: 0
      stamp:
        nsecs: 0
        secs: 0
    joint_names:
    - left_hand_j0
    - left_hand_j1
    - left_hand_j2
    - left_hand_j3
    - left_hand_j4
    points:
    - accelerations: []
      effort: []
      positions:
      - 1.3947399982060031
      - 0.16161399972572643
      - 0.0254732997155211
      - 0.04041141662683649
      - 0.10731468046050929
      time_from_start:
        nsecs: 500000000
        secs: 0
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - 1.3947548046585148
      - 0.15979924552766567
      - 0.026353531167340707
      - 0.04023992340413595
      - 0.10750118724633452
      time_from_start:
        nsecs: 0
        secs: 2
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - 1.4139471595588087
      - 0.1615384207346816
      - 0.026643694074183644
      - 0.04054181744610744
      - 0.1073410727182608
      time_from_start:
        nsecs: 500000000
        secs: 3
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - 1.4141001675140048
      - 0.16103534657793675
      - 0.02253943016004621
      - 0.040219381249190826
      - 0.10585742395940553
      time_from_start:
        nsecs: 0
        secs: 5
      velocities: []
right_arm:
  right_arm_look_at:
    header:
      frame_id: ''
      seq: 0
      stamp:
        nsecs: 0
        secs: 0
    joint_names:
    - right_arm_j0
    - right_arm_j1
    - right_arm_j2
    - right_arm_j3
    - right_arm_j4
    - right_arm_j5
    - right_arm_j6
    points:
    - accelerations: []
      effort: []
      positions:
      - 0.2390638535393412
      - 0.18053310231740716
      - -0.3851816190398909
      - 1.8994474167702942
      - 3.1932890662927926
      - -0.5157339145569018
      - 0.6702131134156939
      time_from_start:
        nsecs: 0
        secs: 2
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - 0.2392719890269187
      - 0.1806538134451575
      - -0.38524431653134616
      - 1.8994619607696637
      - 3.192486939986026
      - -0.5154753666141018
      - 0.6699800528828382
      time_from_start:
        nsecs: 500000000
        secs: 4
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - 0.23930547450401266
      - 0.1781126205797204
      - -0.38332380771726166
      - 1.8995396413908492
      - 3.19330361805799
      - -0.5043348359899097
      - 0.6574238287260776
      time_from_start:
        nsecs: 500000000
        secs: 8
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - 0.0264627837511683
      - 0.05791130936849921
      - -0.36338387832220337
      - 0.3907303528592635
      - 1.636569767567736
      - -0.21055171419407934
      - -0.11006983966065648
      time_from_start:
        nsecs: 500000000
        secs: 10
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - 0.0264627837511683
      - 0.05791130936849921
      - -0.36338387832220337
      - 0.3907303528592635
      - 1.636569767567736
      - -0.21055171419407934
      - -0.11006983966065648
      time_from_start:
        nsecs: 500000000
        secs: 11
      velocities: []
  right_arm_hand_over_retreat:
    header:
      frame_id: ''
      seq: 0
      stamp:
        nsecs: 0
        secs: 0
    joint_names:
    - right_arm_j0
    - right_arm_j1
    - right_arm_j2
    - right_arm_j3
    - right_arm_j4
    - right_arm_j5
    - right_arm_j6
    points:
    - accelerations: []
      effort: []
      positions:
      - -0.15373810606844726
      - 0.06935416423136535
      - -0.3037601903940014
      - 0.3961671822410529
      - 1.6
      - -0.039288431295840566
      - -0.08282746466944946
      time_from_start:
        nsecs: 500000000
        secs: 3
      velocities: []
  right_arm_hand_over_approach_low:
    header:
      frame_id: ''
      seq: 0
      stamp:
        nsecs: 0
        secs: 0
    joint_names:
    - right_arm_j0
    - right_arm_j1
    - right_arm_j2
    - right_arm_j3
    - right_arm_j4
    - right_arm_j5
    - right_arm_j6
    points:
    - accelerations: []
      effort: []
      positions:
      - -0.15373810606844726
      - 0.06935416423136535
      - -0.3037601903940014
      - 0.3961671822410529
      - 1.4045396371605094
      - -0.039288431295840566
      - -0.08282746466944946
      time_from_start:
        nsecs: 500000000
        secs: 0
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - -0.1727549084621605
      - 0.277066690616004
      - -0.3473329117442474
      - 0.9007154064764649
      - 1.423694519608574
      - -0.09903537221164402
      - 0.1571785840253242
      time_from_start:
        nsecs: 0
        secs: 2
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - -0.04967870907855449
      - 0.1481449394117049
      - -0.2692974300021361
      - 1.418884261204355
      - 1.2524042461510012
      - -0.3878655782542377
      - -0.12184789172018813
      time_from_start:
        nsecs: 500000000
        secs: 3
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - -0.05406062258370079
      - 0.06651164526867354
      - -0.26803892139635327
      - 1.1964696941768165
      - 2.0
      - -0.20419839242121857
      - -0.3788778856427268
      time_from_start:
        nsecs: 0
        secs: 5
      velocities: []
  right_arm_hand_over_approach_high:
    header:
      frame_id: ''
      seq: 0
      stamp:
        nsecs: 0
        secs: 0
    joint_names:
    - right_arm_j0
    - right_arm_j1
    - right_arm_j2
    - right_arm_j3
    - right_arm_j4
    - right_arm_j5
    - right_arm_j6
    points:
    - accelerations: []
      effort: []
      positions:
      - -0.15373810606844726
      - 0.06935416423136535
      - -0.3037601903940014
      - 0.3961671822410529
      - 1.4045396371605094
      - -0.039288431295840566
      - -0.08282746466944946
      time_from_start:
        nsecs: 500000000
        secs: 0
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - -0.1727549084621605
      - 0.277066690616004
      - -0.3473329117442474
      - 0.9007154064764649
      - 1.423694519608574
      - -0.09903537221164402
      - 0.1571785840253242
      time_from_start:
        nsecs: 0
        secs: 2
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - -0.04967870907855449
      - 0.1481449394117049
      - -0.2692974300021361
      - 1.418884261204355
      - 1.2524042461510012
      - -0.3878655782542377
      - -0.12184789172018813
      time_from_start:
        nsecs: 500000000
        secs: 3
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - -0.05406062258370079
      - 0.06651164526867354
      - -0.26803892139635327
      - 1.1964696941768165
      - 2.0
      - -0.20419839242121857
      - -0.3788778856427268
      time_from_start:
        nsecs: 0
        secs: 5
      velocities: []
torso:
  right_arm_hand_over_retreat:
    header:
      frame_id: ''
      seq: 0
      stamp:
        nsecs: 0
        secs: 0
    joint_names:
    - torso_j0
    - torso_j1
    points:
    - accelerations: []
      effort: []
      positions:
      - 0.02601425109431393
      - -0.06595714581356243
      time_from_start:
        nsecs: 500000000
        secs: 3
      velocities: []
  right_arm_hand_over_approach_low:
    header:
      frame_id: ''
      seq: 0
      stamp:
        nsecs: 0
        secs: 0
    joint_names:
    - torso_j0
    - torso_j1
    points:
    - accelerations: []
      effort: []
      positions:
      - 0.02601425109431393
      - -0.06595714581356243
      time_from_start:
        nsecs: 500000000
        secs: 0
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - -0.19802758019708658
      - -0.06545744141074289
      time_from_start:
        nsecs: 0
        secs: 2
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - -0.04067694483016635
      - -0.0632842907127689
      time_from_start:
        nsecs: 500000000
        secs: 3
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - -0.040677991313258416
      - -0.06544314050678883
      time_from_start:
        nsecs: 0
        secs: 5
      velocities: []
right_hand:
  right_arm_look_at:
    header:
      frame_id: ''
      seq: 0
      stamp:
        nsecs: 0
        secs: 0
    joint_names:
    - right_hand_j0
    - right_hand_j1
    - right_hand_j2
    - right_hand_j3
    - right_hand_j4
    points:
    - accelerations: []
      effort: []
      positions:
      - 1.9569157146337777
      - 2.7506957043646816
      - 3.4977492684957507
      - 3.316287946676297
      - 2.851095953736346
      time_from_start:
        nsecs: 100000000
        secs: 2
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - 1.9570360631705672
      - 2.750768742121566
      - 3.5021987094435696
      - 1.2588986946213365
      - 0.8858053636241873
      time_from_start:
        nsecs: 100000000
        secs: 3
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - 1.9570360631705672
      - 2.750768742121566
      - 4.0
      - 0.5
      - 0.5
      time_from_start:
        nsecs: 300000000
        secs: 6
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - 1.9
      - 2.5
      - 4.0
      - 4.0
      - 4.0
      time_from_start:
        nsecs: 300000000
        secs: 7
      velocities: []
    - accelerations: []
      effort: []
      positions:
      - 1.9
      - 2.5
      - 4.0
      - 4.0
      - 4.0
      time_from_start:
        nsecs: 700000000
        secs: 10
      velocities: []
  open:
    header:
      frame_id: ''
      seq: 0
      stamp:
        nsecs: 0
        secs: 0
    joint_names:
    - right_hand_j0
    - right_hand_j1
    - right_hand_j2
    - right_hand_j3
    - right_hand_j4
    points:
    - accelerations: []
      effort: []
      positions:
      - 1.35820415002705968
      - 0.160011718754829
      - 0.04992418332867426
      - 0.05997995792206172
      - 0.1592405701581761
      time_from_start:
        nsecs: 0
        secs: 1
      velocities: []

  close:
    header:
      frame_id: ''
      seq: 0
      stamp:
        nsecs: 0
        secs: 0
    joint_names:
    - right_hand_j0
    - right_hand_j1
    - right_hand_j2
    - right_hand_j3
    - right_hand_j4
    points:
    - accelerations: []
      effort: []
      positions:
      - 1.9
      - 2.5
      - 4.0
      - 4.0
      - 4.0
      time_from_start:
        nsecs: 500000000
        secs: 1
      velocities: []