<?xml version="1.0"?>
<robot 
  xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor" 
  xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller" 
  xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace></robotNamespace>
      <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
      <alwaysOn>true</alwaysOn>
      <updateRate>30.0</updateRate>
    </plugin>
<!--   
    <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
      <alwaysOn>1</alwaysOn>
      <updateRate>60.0</updateRate>
      <robotNamespace>/</robotNamespace>
      <leftFrontJoint>front_left_wheel_joint</leftFrontJoint>
      <rightFrontJoint>front_right_wheel_joint</rightFrontJoint>
      <leftRearJoint>back_left_wheel_joint</leftRearJoint>
      <rightRearJoint>back_right_wheel_joint</rightRearJoint>
      <wheelSeparation>1</wheelSeparation>
      <wheelDiameter>${2*wheel_radius}</wheelDiameter>
      <torque>1000</torque>
      <broadcastTF>1</broadcastTF>
      <odometryFrame>map</odometryFrame>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <robotBaseFrame>base_link</robotBaseFrame>
      <covariance_x>0.0001</covariance_x>
      <covariance_y>0.0001</covariance_y>
      <covariance_z>0.0001</covariance_z>
      <covariance_yaw>0.0001</covariance_yaw>
    </plugin> -->

    <plugin name="drive_controller" filename="libgazebo_ros_planar_move.so">
      <odometryRate>60.0</odometryRate>
      <robotNamespace>/</robotNamespace>
      <commandTopic>cmd_vel</commandTopic>
      <robotBaseFrame>base_footprint</robotBaseFrame>
    </plugin>

    <plugin name="mimic_right_j1a" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
      <joint>right_hand_j1</joint>
      <mimicJoint>right_hand_j1a</mimicJoint>
      <multiplier>${th_palmprox_coupling}</multiplier>
      <sensitiveness>0.0</sensitiveness>
    </plugin>

    <plugin name="mimic_right_j1b" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
      <joint>right_hand_j1</joint>
      <mimicJoint>right_hand_j1b</mimicJoint>
      <multiplier>${th_proxdist_coupling}</multiplier>
      <sensitiveness>0.0</sensitiveness>
    </plugin>

    <!-- j2 -->
    <plugin name="mimic_right_j2a" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
      <joint>right_hand_j2</joint>
      <mimicJoint>right_hand_j2a</mimicJoint>
      <multiplier>${palmprox_coupling}</multiplier>
      <sensitiveness>0.0</sensitiveness>
    </plugin>

    <plugin name="mimic_right_j2b" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
      <joint>right_hand_j2</joint>
      <mimicJoint>right_hand_j2b</mimicJoint>
      <multiplier>${proxmid_coupling}</multiplier>
      <sensitiveness>0.0</sensitiveness>
    </plugin>

    <plugin name="mimic_right_j2c" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
      <joint>right_hand_j2</joint>
      <mimicJoint>right_hand_j2c</mimicJoint>
      <multiplier>${middist_coupling}</multiplier>
      <sensitiveness>0.0</sensitiveness>
    </plugin>

    <!-- j3 -->
   <plugin name="mimic_right_j3a" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
      <joint>right_hand_j3</joint>
      <mimicJoint>right_hand_j3a</mimicJoint>
      <multiplier>${palmprox_coupling}</multiplier>
      <sensitiveness>0.0</sensitiveness>
    </plugin>

    <plugin name="mimic_right_j3b" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
      <joint>right_hand_j3</joint>
      <mimicJoint>right_hand_j3b</mimicJoint>
      <multiplier>${proxmid_coupling}</multiplier>
      <sensitiveness>0.0</sensitiveness>
    </plugin>

    <plugin name="mimic_right_j3c" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
      <joint>right_hand_j3</joint>
      <mimicJoint>right_hand_j3c</mimicJoint>
      <multiplier>${middist_coupling}</multiplier>
      <sensitiveness>0.0</sensitiveness>
    </plugin>

    <!-- j4 -->
    <plugin name="mimic_right_j4a" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
      <joint>right_hand_j4</joint>
      <mimicJoint>right_hand_j4a</mimicJoint>
      <multiplier>${palmprox_coupling}</multiplier>
      <sensitiveness>0.0</sensitiveness>
    </plugin>

    <plugin name="mimic_right_j4b" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
      <joint>right_hand_j4</joint>
      <mimicJoint>right_hand_j4b</mimicJoint>
      <multiplier>${proxmid_coupling}</multiplier>
      <sensitiveness>0.0</sensitiveness>
    </plugin>

    <plugin name="mimic_right_j4c" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
      <joint>right_hand_j4</joint>
      <mimicJoint>right_hand_j4c</mimicJoint>
      <multiplier>${middist_coupling}</multiplier>
      <sensitiveness>0.0</sensitiveness>
    </plugin>

  </gazebo>

</robot>