<?xml version="1.0"?>
<robot 
  xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor" 
  xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller" 
  xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
  xmlns:xacro="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/meka_roscontrol</robotNamespace>
      <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
      <alwaysOn>true</alwaysOn>
      <updateRate>30.0</updateRate>
    </plugin>
        
    <!--plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
      <alwaysOn>1</alwaysOn>
      <updateRate>100.0</updateRate>
      <robotNamespace>/</robotNamespace>
      <leftFrontJoint>front_left_wheel_joint</leftFrontJoint>
      <rightFrontJoint>front_right_wheel_joint</rightFrontJoint>
      <leftRearJoint>back_left_wheel_joint</leftRearJoint>
      <rightRearJoint>back_right_wheel_joint</rightRearJoint>
      <wheelSeparation>0.2678</wheelSeparation>
      <wheelDiameter>${2*wheel_radius}</wheelDiameter>
      <torque>10</torque>
      <broadcastTF>1</broadcastTF>
      <odometryFrame>map</odometryFrame>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <robotBaseFrame>base_link</robotBaseFrame>
      <covariance_x>0.0001</covariance_x>
      <covariance_y>0.0001</covariance_y>
      <covariance_z>0.0001</covariance_z>
      <covariance_yaw>0.0001</covariance_yaw>O
    </plugin--> 
    

    <plugin name="object_controller" filename="libgazebo_ros_planar_move.so">
      <commandTopic>smooth_cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <odometryRate>20.0</odometryRate>
      <robotBaseFrame>base_link</robotBaseFrame>
      <joint_state_idel_sec>2.0</joint_state_idel_sec>
      <recover_roll_velocity_p_gain>50.0</recover_roll_velocity_p_gain>
      <recover_pitch_velocity_p_gain>50.0</recover_pitch_velocity_p_gain>
      <recover_z_velocity_p_gain>1.0</recover_z_velocity_p_gain>
      <x_velocity_limit_max>4.0</x_velocity_limit_max>
      <x_velocity_limit_min>-4.0</x_velocity_limit_min>
      <y_velocity_limit_max>4.0</y_velocity_limit_max>
      <y_velocity_limit_min>-4.0</y_velocity_limit_min>
      <rot_velocity_limit_max>3.0</rot_velocity_limit_max>
      <rot_velocity_limit_min>-3.0</rot_velocity_limit_min>
      <x_acceleration_limit_max>3.0</x_acceleration_limit_max>
      <x_acceleration_limit_min>-3.0</x_acceleration_limit_min>
      <y_acceleration_limit_max>3.0</y_acceleration_limit_max>
      <y_acceleration_limit_min>-3.0</y_acceleration_limit_min>
      <rot_acceleration_limit_max>2.0</rot_acceleration_limit_max>
      <rot_acceleration_limit_min>-2.0</rot_acceleration_limit_min>
      <tilt_angle_par_max_velocity>1</tilt_angle_par_max_velocity>
    </plugin>
    
    <xacro:if value="$(arg _torso)">
        <plugin name="mimic_torso" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
            <joint>torso_j1</joint>
            <mimicJoint>torso_j2</mimicJoint>
            <multiplier>1.0</multiplier>
            <!--offset>0.0</offset-->
        </plugin>
    </xacro:if>
    
    <xacro:if value="$(arg _r_hand)">
        <plugin name="mimic_right_j1a" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
          <joint>right_hand_j1</joint>
          <mimicJoint>right_hand_j1a</mimicJoint>
          <multiplier>${th_palmprox_coupling}</multiplier>
          <sensitiveness>0.0</sensitiveness>
        </plugin>

        <plugin name="mimic_right_j1b" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
          <joint>right_hand_j1</joint>
          <mimicJoint>right_hand_j1b</mimicJoint>
          <multiplier>${th_proxdist_coupling}</multiplier>
          <sensitiveness>0.0</sensitiveness>
        </plugin>

        <plugin name="mimic_right_j2a" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
          <joint>right_hand_j2</joint>
          <mimicJoint>right_hand_j2a</mimicJoint>
          <multiplier>${palmprox_coupling}</multiplier>
          <sensitiveness>0.0</sensitiveness>
        </plugin>

        <plugin name="mimic_right_j2b" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
          <joint>right_hand_j2</joint>
          <mimicJoint>right_hand_j2b</mimicJoint>
          <multiplier>${proxmid_coupling}</multiplier>
          <sensitiveness>0.0</sensitiveness>
        </plugin>

        <plugin name="mimic_right_j2c" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
          <joint>right_hand_j2</joint>
          <mimicJoint>right_hand_j2c</mimicJoint>
          <multiplier>${middist_coupling}</multiplier>
          <sensitiveness>0.0</sensitiveness>
        </plugin>

       <plugin name="mimic_right_j3a" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
          <joint>right_hand_j3</joint>
          <mimicJoint>right_hand_j3a</mimicJoint>
          <multiplier>${palmprox_coupling}</multiplier>
          <sensitiveness>0.0</sensitiveness>
        </plugin>

        <plugin name="mimic_right_j3b" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
          <joint>right_hand_j3</joint>
          <mimicJoint>right_hand_j3b</mimicJoint>
          <multiplier>${proxmid_coupling}</multiplier>
          <sensitiveness>0.0</sensitiveness>
        </plugin>

        <plugin name="mimic_right_j3c" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
          <joint>right_hand_j3</joint>
          <mimicJoint>right_hand_j3c</mimicJoint>
          <multiplier>${middist_coupling}</multiplier>
          <sensitiveness>0.0</sensitiveness>
        </plugin>

        <plugin name="mimic_right_j4a" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
          <joint>right_hand_j4</joint>
          <mimicJoint>right_hand_j4a</mimicJoint>
          <multiplier>${palmprox_coupling}</multiplier>
          <sensitiveness>0.0</sensitiveness>
        </plugin>

        <plugin name="mimic_right_j4b" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
          <joint>right_hand_j4</joint>
          <mimicJoint>right_hand_j4b</mimicJoint>
          <multiplier>${proxmid_coupling}</multiplier>
          <sensitiveness>0.0</sensitiveness>
        </plugin>

        <plugin name="mimic_right_j4c" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
          <joint>right_hand_j4</joint>
          <mimicJoint>right_hand_j4c</mimicJoint>
          <multiplier>${middist_coupling}</multiplier>
          <sensitiveness>0.0</sensitiveness>
        </plugin>
  </xacro:if>
  
  <xacro:if value="$(arg _l_hand)">
        <plugin name="mimic_left_j1a" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
          <joint>left_hand_j1</joint>
          <mimicJoint>left_hand_j1a</mimicJoint>
          <multiplier>${th_palmprox_coupling}</multiplier>
          <sensitiveness>0.0</sensitiveness>
        </plugin>

        <plugin name="mimic_left_j1b" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
          <joint>left_hand_j1</joint>
          <mimicJoint>left_hand_j1b</mimicJoint>
          <multiplier>${th_proxdist_coupling}</multiplier>
          <sensitiveness>0.0</sensitiveness>
        </plugin>

        <plugin name="mimic_left_j2a" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
          <joint>left_hand_j2</joint>
          <mimicJoint>left_hand_j2a</mimicJoint>
          <multiplier>${palmprox_coupling}</multiplier>
          <sensitiveness>0.0</sensitiveness>
        </plugin>

        <plugin name="mimic_left_j2b" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
          <joint>left_hand_j2</joint>
          <mimicJoint>left_hand_j2b</mimicJoint>
          <multiplier>${proxmid_coupling}</multiplier>
          <sensitiveness>0.0</sensitiveness>
        </plugin>

        <plugin name="mimic_left_j2c" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
          <joint>left_hand_j2</joint>
          <mimicJoint>left_hand_j2c</mimicJoint>
          <multiplier>${middist_coupling}</multiplier>
          <sensitiveness>0.0</sensitiveness>
        </plugin>

       <plugin name="mimic_left_j3a" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
          <joint>left_hand_j3</joint>
          <mimicJoint>left_hand_j3a</mimicJoint>
          <multiplier>${palmprox_coupling}</multiplier>
          <sensitiveness>0.0</sensitiveness>
        </plugin>

        <plugin name="mimic_left_j3b" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
          <joint>left_hand_j3</joint>
          <mimicJoint>left_hand_j3b</mimicJoint>
          <multiplier>${proxmid_coupling}</multiplier>
          <sensitiveness>0.0</sensitiveness>
        </plugin>

        <plugin name="mimic_left_j3c" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
          <joint>left_hand_j3</joint>
          <mimicJoint>left_hand_j3c</mimicJoint>
          <multiplier>${middist_coupling}</multiplier>
          <sensitiveness>0.0</sensitiveness>
        </plugin>

        <plugin name="mimic_left_j4a" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
          <joint>left_hand_j4</joint>
          <mimicJoint>left_hand_j4a</mimicJoint>
          <multiplier>${palmprox_coupling}</multiplier>
          <sensitiveness>0.0</sensitiveness>
        </plugin>

        <plugin name="mimic_left_j4b" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
          <joint>left_hand_j4</joint>
          <mimicJoint>left_hand_j4b</mimicJoint>
          <multiplier>${proxmid_coupling}</multiplier>
          <sensitiveness>0.0</sensitiveness>
        </plugin>

        <plugin name="mimic_left_j4c" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
          <joint>left_hand_j4</joint>
          <mimicJoint>left_hand_j4c</mimicJoint>
          <multiplier>${middist_coupling}</multiplier>
          <sensitiveness>0.0</sensitiveness>
        </plugin>
  </xacro:if>

  </gazebo>

  <gazebo reference="laser_front">
    <sensor type="gpu_ray" name="front_laser_sim">
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>30</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-${4.71239/2}</min_angle>
            <max_angle>${4.71239/2}</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.20</min>
          <max>30.0</max>
          <resolution>0.004363323</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.005</stddev>
        </noise>
      </ray>
      <plugin name="laser_front_hokuyo" filename="libgazebo_ros_gpu_laser.so">
        <topicName>/scan_front</topicName>
        <frameName>laser_front</frameName>
      </plugin>
    </sensor>
  </gazebo>

  <gazebo reference="laser_rear">
    <sensor type="gpu_ray" name="rear_laser_sim">
      <pose>0 0 0 0 0 0 </pose>
      <visualize>false</visualize>
      <update_rate>15</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-1.570796</min_angle>
            <max_angle>1.570796</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.2</min>
          <max>25.0</max>
          <resolution>0.005759587</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.03</stddev>
        </noise>
      </ray>
      <plugin name="laser_rear_sick" filename="libgazebo_ros_gpu_laser.so">
        <topicName>/scan_rear</topicName>
        <frameName>laser_rear</frameName>
      </plugin>
    </sensor>
  </gazebo>

</robot>
