joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

head_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - head_j0
      - head_j1
    gains:
      head_j0: {p: 100,  d: 1, i: 1, i_clamp: 1} 
      head_j1: {p: 100,  d: 1, i: 1, i_clamp: 1}

zlift_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - zlift_j0
    gains:
      zlift_j0: {p: 100,  d: 1, i: 1, i_clamp: 1} 

body_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - torso_j0
      - torso_j1
    gains:
      torso_j0: {p: 100,  d: 1, i: 1, i_clamp: 1}
      torso_j1: {p: 100,  d: 1, i: 1, i_clamp: 1}  

arm_r_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - right_arm_j0
      - right_arm_j1
      - right_arm_j2
      - right_arm_j3
      - right_arm_j4
      - right_arm_j5
      - right_arm_j6
    gains:
      right_arm_j0: {p: 100,  d: 1, i: 1, i_clamp: 1}
      right_arm_j1: {p: 100,  d: 1, i: 1, i_clamp: 1} 
      right_arm_j2: {p: 100,  d: 1, i: 1, i_clamp: 1}
      right_arm_j3: {p: 100,  d: 1, i: 1, i_clamp: 1}  
      right_arm_j4: {p: 100,  d: 1, i: 1, i_clamp: 1}
      right_arm_j5: {p: 100,  d: 1, i: 1, i_clamp: 1}
      right_arm_j6: {p: 100,  d: 1, i: 1, i_clamp: 1}   

hand_r_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - right_hand_j0
      - right_hand_j1
      - right_hand_j2
      - right_hand_j3
      - right_hand_j4
    gains:
      right_hand_j0: {p: 100,  d: 1, i: 1, i_clamp: 1}
      right_hand_j1: {p: 100,  d: 1, i: 1, i_clamp: 1} 
      right_hand_j2: {p: 100,  d: 1, i: 1, i_clamp: 1}
      right_hand_j3: {p: 100,  d: 1, i: 1, i_clamp: 1}  
      right_hand_j4: {p: 100,  d: 1, i: 1, i_clamp: 1}  
    
arm_l_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - left_arm_j0
      - left_arm_j1
      - left_arm_j2
      - left_arm_j3
      - left_arm_j4
      - left_arm_j5
      - left_arm_j6
    gains:
      left_arm_j0: {p: 100,  d: 1, i: 1, i_clamp: 1}
      left_arm_j1: {p: 100,  d: 1, i: 1, i_clamp: 1} 
      left_arm_j2: {p: 100,  d: 1, i: 1, i_clamp: 1}
      left_arm_j3: {p: 100,  d: 1, i: 1, i_clamp: 1}  
      left_arm_j4: {p: 100,  d: 1, i: 1, i_clamp: 1}
      left_arm_j5: {p: 100,  d: 1, i: 1, i_clamp: 1}
      left_arm_j6: {p: 100,  d: 1, i: 1, i_clamp: 1}   

hand_l_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - left_hand_j0
      - left_hand_j1
      - left_hand_j2
      - left_hand_j3
      - left_hand_j4
    gains:
      left_hand_j0: {p: 100,  d: 1, i: 1, i_clamp: 1}
      left_hand_j1: {p: 100,  d: 1, i: 1, i_clamp: 1} 
      left_hand_j2: {p: 100,  d: 1, i: 1, i_clamp: 1}
      left_hand_j3: {p: 100,  d: 1, i: 1, i_clamp: 1}  
      left_hand_j4: {p: 100,  d: 1, i: 1, i_clamp: 1}  
