xsc3_server:
  humotion:
    configuration: {breath_amplitude: 1.0, breath_period: 4.5, eyeblink_blocked_time: 10.989,
      eyeblink_duration: 0.2574, eyeblink_periodic_distribution_lower: 99.90000000000002,
      eyeblink_periodic_distribution_upper: 99.90000000000002, eyeblink_probability_after_saccade: 0.2,
      eyelids_follow_eyemotion: true, limit_acceleration_eye: 80000.0, limit_acceleration_neck: 1089.0,
      limit_mr_neck: 0.882, limit_omr_eye: 0.855, limit_velocity_eye: 700.0, limit_velocity_neck: 364.0,
      publish_internals: false, scale_acceleration_eye: 1.0, scale_acceleration_neck: 0.441,
      scale_velocity_eye: 0.45, scale_velocity_neck: 0.504, threshold_angle_neck_saccade: 15.0,
      threshold_angle_omr_limit: 0.35, threshold_velocity_eye_saccade: 15.0, use_neck_target_instead_of_position_eye: true}
